swagger: "2.0"
info:
  description: "Renten Antrag Prozesse"
  version: "1.0.0"
  title: "Swagger Rap"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "liubov.dauer@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/rav/api/v1/antrag"
tags:
- name: "antrag"
  description: "Rap"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "https"
- "http"
paths:
  /antrag:
    post:
      tags:
      - "antrag"
      summary: "Einen neuen Antrag anlegen"
      description: ""
      operationId: "antragAnlegen"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Daten für einen neuen Antrag"
        required: false
        schema:
          $ref: "#/definitions/Antrag"
      responses:
        "200":
          description: "Der Antrag ist angegangen"
      
definitions:
  Antrag:
    type: "object"
    properties:
        Person:
          type: "object"
          required:
          - "vorname"
          properties:
            vorname:
              type: "string"
            nachname:
              type: "string"
    xml:
      name: "Person"
  ApiResponse:
    type: "object"
    required:
        - "istGenehmigt"
    properties:
      istGenehmigt:
        type: "boolean"
      businessPartnerId:
        type: "string"
      antragId:  
        type: "integer"
        format: "int64"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"